define ->
  findingRoutes: 'Finding routes...'
  earlierDepartures: "Earlier departures"
  laterDepartures: "Later departures"
  earlierArrivals: "Earlier arrivals"
  laterArrivals: "Later arrivals"
  departure: 'Departure'
  arrival: 'Arrival'
  duration: 'Duration'
  walkingDistance: 'Walk'
  routeTo: 'Directions to here'
  routeFrom: 'Directions from here'
  warning: 'Oh snap'
  geolocationError: 'We were unable to locate you.'
  geolocating: 'Determining your location…'
  favorites: 'Favorites'
  add: 'Add'
  newFavorite: 'New favourite'
  editFavorites: 'Edit favourites'
  noFavorites: 'No favourites'

  transportType:
    walk: 'Walk'
    1: 'Bus'
    2: 'Tram'
    3: 'Bus'
    4: 'Bus'
    5: 'Bus'
    6: 'Metro'
    7: 'Ferry'
    8: 'Bus'
    12: 'Train'
    21: 'Bus'
    22: 'Bus'
    23: 'Bus'
    24: 'Bus'
    25: 'Bus'
    26: 'Bus'
    36: 'Bus'
    39: 'Bus'
  boardingLabel:
    1: 'To bus'
    2: 'To tram'
    3: 'To bus'
    4: 'To bus'
    5: 'To bus'
    6: 'To metro'
    7: 'To ferry'
    8: 'To bus'
    12: 'To train'
    21: 'To bus'
    22: 'To bus'
    23: 'To bus'
    24: 'To bus'
    25: 'To bus'
    26: 'To bus'
    36: 'To bus'
    39: 'To bus'

