
define ->
  transportTypeSelector:
    bus: 'Bussit'
    tram: 'Ratikat'
    metro: 'Metrot'
    train: 'Junat'
    ferry: 'Lautat'
  from: 'Mistä'
  to: 'Mihin'
  departureTime: 'Lähtöaika'
  arrivalTime: 'Perillä'
  findRoutes: 'Hae reitit'
  findingRoutes: 'Haetaan reittejä...'
  earlierDepartures: "Aikaisemmat lähdöt"
  laterDepartures: "Myöhemmät lähdöt"
  earlierArrivals: "Aikaisemmin perillä"
  laterArrivals: "Myöhemmin perillä"
  departure: 'Lähtö'
  arrival: 'Perillä'
  duration: 'Kesto'
  walkingDistance: 'Kävelyä'
  transportType:
    walk: 'Kävely'
    1: 'Bussi'
    2: 'Ratikka'
    3: 'Bussi'
    4: 'Bussi'
    5: 'Bussi'
    6: 'Metro'
    7: 'Lautta'
    8: 'Bussi'
    12: 'Juna'
    21: 'Bussi'
    22: 'Bussi'
    23: 'Bussi'
    24: 'Bussi'
    25: 'Bussi'
    26: 'Bussi'
    36: 'Bussi'
    39: 'Bussi'
  boardingLabel:
    1: 'Bussiin'
    2: 'Ratikkaan'
    3: 'Bussiin'
    4: 'Bussiin'
    5: 'Bussiin'
    6: 'Metroon'
    7: 'Lauttaan'
    8: 'Bussiin'
    12: 'Junaan'
    21: 'Bussiin'
    22: 'Bussiin'
    23: 'Bussiin'
    24: 'Bussiin'
    25: 'Bussiin'
    26: 'Bussiin'
    36: 'Bussiin'
    39: 'Bussiin'
  competitionEntry: 'Apps4Finland-kilpailutyö'
  routeData: 'Reittitiedot'
  sourceCode: 'Lähdekoodi ja tietoa'
  feedback: 'Palaute'